namespace NodeJS {
	interface ProcessEnv {
		NEXT_PUBLIC_EMAILJS_SERVICE_ID: string;
		NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: string;
		NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: string;
		NEXT_PUBLIC_RECAPTCHA_PUBLIC_KEY: string;
		#RECAPTCHA_PRIVATE_KEY_FOR_EMAILJS: string;
		NEXT_PUBLIC_DEV_MAIL_USER: string;
		NEXT_PUBLIC_DEV_MAIL_PROVIDER: string;
		NEXT_PUBLIC_DEV_LINKEDIN: string;
		NEXT_PUBLIC_DEV_X: string;
		NEXT_PUBLIC_DEV_FACEBOOK: string;
		NEXT_PUBLIC_DEV_INSTAGRAM: string;
		NEXT_PUBLIC_DEV_GITHUB: string;
		NEXT_PUBLIC_DEV_DEVTO: string;
		NEXT_PUBLIC_SITE_URL: string;
		BLOG_POST_PER_PAGE: string;
		APP_URL: string;
	}
}
