import Navbar from "@/components/navbar";
import NavbarProvider from "@/components/navbar/navbar-provider";
import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata, Viewport } from "next";
import { Noto_Sans_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";

const notoSansMono = Noto_Sans_Mono({
	variable: "--font-noto-sans-mono",
	subsets: ["latin-ext"],
	preload: false
});

const poppins = Poppins({
	weight: ["400", "500", "600", "700", "800", "900"],
	variable: "--font-poppins",
	subsets: ["latin-ext"],
	preload: false
});

export const metadata: Metadata = {
	title: {
		default: "Donis.Dev Fullstack Developer",
		template: "%s | Donis.Dev Fullstack Developer",
	},
	description: "Generated by create next app",
};

export const viewport: Viewport = {
	width: "device-width",
	initialScale: 1,
	maximumScale: 1,
	userScalable: false,
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${poppins.variable} ${notoSansMono.variable}  flex min-h-dvh flex-col justify-between antialiased`}
			>
				<ThemeProvider>
					<NavbarProvider>
						<Navbar />
						{children}
						<Footer />
					</NavbarProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
